config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # Define a rota padrão
  root to: "welcome#index" #"accounts#index"

  resources :transactions
  resources :accounts
  resources :agencies

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]
  before_action :initialize_dependences, only: [:new, :edit, :create, :update]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.where(account_id: current_user.accounts.ids).or(Transaction.where(account_destiny_id: current_user.accounts.ids)).page(params[:page]).per(5)
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new(transaction_type: params[:transaction_type])
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params.merge!(user_id: current_user.id))
    begin
      respond_to do |format|
        if @transaction.save!
          format.html { redirect_to @transaction, notice: "Transaction was successfully created." }
          format.json { render :show, status: :created, location: @transaction }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @transaction.errors, status: :unprocessable_entity }
        end
      end
    rescue => exception
      render :new
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params.merge!(user_id: current_user.id))
        format.html { redirect_to @transaction, notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "You can't remove an transaction!" }
      format.json { head :no_content }
    end
  end

  private

    def initialize_dependences
      @accounts = current_user.accounts
      @accounts_destiny = Account.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:date, :amount, :transaction_type, :account_id, :user_id, :account_destiny_id)
    end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :transaction_type %>
    <% form.number_field :transaction_type %>
    <%= transaction.transaction_type.upcase %>
    <%= form.hidden_field :transaction_type%>
    <% form.select :transaction_type, options_for_select(Transaction::transaction_types.map {|key, value| [key.titleize, Transaction.transaction_types.key(value)]}, transaction.transaction_type), {:disabled => true}%>
  </div>

  <div class="field">
    <%= form.label :account_id %>
    <%= form.select :account_id, options_for_select(@accounts.map{|account| [account.format_description, account.id]}, transaction.account_id) %>
  </div>

  <% if transaction.transfer? %>
    <div class="field">
      <%= form.label :account_destiny_id %>
      <%= form.select :account_destiny_id, options_for_select(@accounts_destiny.map{|account_destiny| [account_destiny.format_description, account_destiny.id]}, transaction.account_destiny_id) %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= current_user.email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<div>
  <h1>Transactions</h1>

  <p>
    <%= link_to 'Deposit',  new_transaction_path(transaction_type: :deposit ), class:"btn btn-lg btn-default" %>
    <%= link_to 'Withdraw', new_transaction_path(transaction_type: :withdraw), class:"btn btn-lg btn-default" %>
    <%= link_to 'Reversal', new_transaction_path(transaction_type: :reversal), class:"btn btn-lg btn-default" %>
    <%= link_to 'Transfer', new_transaction_path(transaction_type: :transfer), class:"btn btn-lg btn-default" %>
  </p>

  </table>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Date</th>
        <th scope="col">User</th>
        <th scope="col">Amount</th>
        <th scope="col">Transaction type</th>
        <th scope="col">Account</th>
        <th scope="col">Account Destiny</th>
      </tr>
    </thead>
    <tbody>
      <% @transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.id %></td>
          <td><%= transaction.date %></td>
          <td><%= transaction.user.email %></td>
          <td><%= transaction.amount %></td>
          <td><%= transaction.transaction_type %></td>
          <td><%= transaction.account.format_description %></td>
          <td><%= transaction.try(:account_destiny).try(:format_description) %></td>
          <td><%= link_to 'Show', transaction %></td>
          <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
          <td><%#= link_to 'Destroy', transaction_path(transaction), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="text-center">
    <%= paginate @transactions %>
  </div>
</div>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @transaction.date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Transaction type:</strong>
  <%= @transaction.transaction_type.upcase %>
</p>

<p>
  <strong>Account ID:</strong>
  <%= @transaction.account_id %>
</p>

<p>
  <strong>User ID:</strong>
  <%= @transaction.user_id %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>