config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # Define a rota padrão
  root to: "welcome#index" #"accounts#index"

  resources :transactions
  resources :accounts
  resources :agencies

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :agency
  belongs_to :user

  has_many :transactions, class_name: "Transaction", dependent: :restrict_with_exception

  validates :number, presence: true, uniqueness: true
  validates :limit, presence: true, numericality: true
  validates :agency_id, presence: true
  validates :balance, presence: true

  before_validation :load_defaults

  def load_defaults
      if self.new_record? && self.balance.to_f <= 0
        self.balance = 0.00
      end
  end

  def account_balance
    deposits = transactions.deposit.sum(:amount).to_f
    withdraws = transactions.withdraw.sum(:amount).to_f
    reversals = transactions.reversal.sum(:amount).to_f
    origin_transfers = transactions.transfer.sum(:amount).to_f
    destiny_transfers = Transaction.transfer.where(account_destiny_id: self.id).sum(:amount).to_f

    (deposits + destiny_transfers) - reversals - withdraws - origin_transfers
  end

  def format_description
    "CC: #{number.to_s} / AG: #{agency.number.to_s}"
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params.merge!(user_id: current_user.id))

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params.merge!(user_id: current_user.id))
        format.html { redirect_to @account, notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    begin
      @account.destroy
      respond_to do |format|
        format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
        format.json { head :no_content }
      end
    rescue => exception
      respond_to do |format|
        format.html { redirect_to accounts_url, notice: "Account can't destroyed: #{exception.message}" }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:number, :limit, :agency_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :limit %>
    <%= form.number_field :limit %>
  </div>

  <div class="field">
    <%= form.label :agency_id %>
    <%= form.select :agency_id, options_for_select(Agency.all.map{|agency| [agency.agency_format, agency.id]}, account.agency_id)%>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= current_user.email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<div>
  <h1>Accounts</h1>

  <p>
    <%= link_to 'New Account', new_account_path, class:"btn btn-lg btn-default" %>
  </p>

  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">User</th>
        <th scope="col">Number</th>
        <th scope="col">Balance</th>
        <th scope="col">Limit</th>
        <th scope="col">Agency</th>
      </tr>
    </thead>
    <tbody>
      <% @accounts.each do |account| %>
        <tr>
          <td><%= account.id %></td>
          <td><%= account.user.email %></td>
          <td><%= account.number %></td>
          <td><%= account.account_balance %></td>
          <td><%= account.limit %></td>
          <td><%= account.agency.address %></td>
          <td><%= link_to 'Show', account %></td>
          <td><%= link_to 'Edit', edit_account_path(account) %></td>
          <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure? This account can have transactions.' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p>
  <strong>Number:</strong>
  <%= @account.number %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @account.balance %>
</p>

<p>
  <strong>Limit:</strong>
  <%= @account.limit %>
</p>

<p>
  <strong>Agency:</strong>
  <%= @account.agency.address %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>